apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-obs-app
  namespace: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-obs-app
  template:
    metadata:
      labels:
        app: demo-obs-app
    spec:
      containers:
      - name: demo-obs-app
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8080
