apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-obs-app
  namespace: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-obs-app
  template:
    metadata:
      labels:
        app: demo-obs-app
    spec:
      containers:
      - name: demo-obs-app
        image: gcr.io/lexical-cider-482012-i7/demo-obs-app:latest
        ports:
        - containerPort: 8080
