name: Build & Deploy to GKE

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: demo-obs-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GKE_OBS_KEY }}

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Configure Docker for GCR
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Build Docker image
      run: |
        docker build -t gcr.io/$PROJECT_ID/$IMAGE:${{ github.sha }} .
        docker tag gcr.io/$PROJECT_ID/$IMAGE:${{ github.sha }} gcr.io/$PROJECT_ID/$IMAGE:latest

    - name: Push Docker image
      run: |
        docker push gcr.io/$PROJECT_ID/$IMAGE:${{ github.sha }}
        docker push gcr.io/$PROJECT_ID/$IMAGE:latest

    - name: Install GKE auth plugin
      run: |
           gcloud components install gke-gcloud-auth-plugin --quiet

    - name: Get GKE credentials
      run: |
          gcloud container clusters get-credentials obs-cluster \
          --zone us-central1-a \
          --project lexical-cider-482012-i7

    - name: Deploy to GKE
      run: |
          sed -i "s|IMAGE_PLACEHOLDER|$IMAGE|g" k8s/deployment.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

    - name: Deploy to GKE
      run: |
        sed -i "s/PROJECT_ID/$PROJECT_ID/g" k8s/deployment.yaml
        kubectl apply -f k8s/
